### ISSUE TITLE
Lamps do not work when they are duplifaces/vertices

### ISSUE THREAD

**Issue by TynkaTopi** [TheBounty/Core#15]
Reproduce:Select lamp and cube, set parent and dupliverts.
Traceback (most recent call last):
  File "C:\Blender\2.72\scripts\addons\thebounty\io\yaf_export.py", line 377, in
 update
    self.exportScene()# to above, line 92
  File "C:\Blender\2.72\scripts\addons\thebounty\io\yaf_export.py", line 114, in
 exportScene
    self.exportObjects()
  File "C:\Blender\2.72\scripts\addons\thebounty\io\yaf_export.py", line 192, in
 exportObjects
    self.yaf_object.writeMesh(obj_dupli.object, matrix)
  File "C:\Blender\2.72\scripts\addons\thebounty\io\yaf_object.py", line 240, in
 writeMesh
    self.writeGeometry(ID, object, matrix)  # obType in 0, default, the object i
s rendered
  File "C:\Blender\2.72\scripts\addons\thebounty\io\yaf_object.py", line 369, in
 writeGeometry
    mesh = obj.to_mesh(self.scene, True, 'RENDER')
RuntimeError: Error: Object does not have geometry data

**Comment by povmaniaco** [comment]
Instead any bug, this issue seems an logical bad workflow: lamp is not geometry object. For this reason object.to_mesh don't work properly. Try to create parent object after of applied the dupliverts operators
